### ISSUE TITLE
Vertical metrics

### ISSUE THREAD

**Issue by m4rc1e** [canonical/Ubuntu-fonts#100]
I'll spend some time working out the optimal values so we get no regressions against the previous static fonts. This may break the existing FB tests but I believe having the same line heights as the previous version is more important.

**Comment by m4rc1e** [comment]
I've done several attempts and we're not going to be able visually match the previous vertical metrics so let's keep what you've got.

Since the win, typo and hhea are all different in the original fonts, it is impossible to get them visually match unless we inherit the old metrics. However, if we inherit the old metrics, then some glyphs will get clipped because the winAscent is lower than several glyphs in the font,

**Comment by djrrb** [comment]
If that works for you, it works for me! We [discussed this a bit](https://github.com/canonical/Ubuntu-fonts/issues/14) and since there are other breaking changes in this update as well, it seemed like if we were gonna change anything now was the time.
