### ISSUE TITLE
Spacing diacritics are ligated into non-spacing diacritics

### ISSUE THREAD

**Issue by dscorbett** [canonical/Ubuntu-fonts#105]
Some pairs of spacing diacritics are ligated into non-spacing diacritics:

* <U+00A8 DIAERESIS, U+00B4 ACUTE ACCENT>
* <U+00A8 DIAERESIS, U+02D8 BREVE>
* <U+00A8 DIAERESIS, U+0060 GRAVE ACCENT>
* <U+00A8 DIAERESIS, U+00AF MACRON>
* <U+02DA RING ABOVE, U+00B4 ACUTE ACCENT>
* <U+02DC SMALL TILDE, U+00AF MACRON>

Here they are, with ⟨e⟩ between the ligatures so they don’t overlap each other:
![e¨´e¨˘e¨`e¨¯e˚´e˜¯](https://github.com/canonical/Ubuntu-fonts/assets/1124347/c4f69c78-689c-4fcd-823c-949fea800f0c)

They should remain individually spacing and should not be ligated; cf. the correct rendering in Noto Sans:
![e¨´e¨˘e¨`e¨¯e˚´e˜¯](https://github.com/canonical/Ubuntu-fonts/assets/1124347/45794e60-09ba-4cd9-b7eb-e22d67c8ba1b)

**Comment by djrrb** [comment]
Thank you! As of f74f1415f90c4582d0b07c7cb87ea2f6451cfb13 these now appear as expected.

<img width="1829" alt="Screenshot 2023-08-02 at 2 57 47 PM" src="https://github.com/canonical/Ubuntu-fonts/assets/6578861/129f9c63-2fb7-440d-991c-75ff52c1341f">

Test string:
```
e¨´e¨˘e¨¯e˚¯e˜¯
```
