### ISSUE TITLE
Spacing Greek diacritics are treated like combining marks

### ISSUE THREAD

**Issue by dscorbett** [canonical/Ubuntu-fonts#107]
Some spacing Greek diacritics combine with preceding glyphs. Their anchor points should be removed so they can be spacing.

* U+0384 GREEK TONOS
* U+0385 GREEK DIALYTIKA TONOS
* U+1FBE GREEK PROSGEGRAMMENI
* U+1FBF GREEK PSILI
* U+1FC0 GREEK PERISPOMENI
* U+1FC1 GREEK DIALYTIKA AND PERISPOMENI
* U+1FCD GREEK PSILI AND VARIA
* U+1FCE GREEK PSILI AND OXIA
* U+1FCF GREEK PSILI AND PERISPOMENI
* U+1FDD GREEK DASIA AND VARIA
* U+1FDE GREEK DASIA AND OXIA
* U+1FDF GREEK DASIA AND PERISPOMENI
* U+1FED GREEK DIALYTIKA AND VARIA
* U+1FEF GREEK VARIA
* U+1FFD GREEK OXIA
* U+1FFE GREEK DASIA

![α΄α΅αια᾿α῀α῁α῍α῎α῏α῝α῞α῟α῭α`α´α῾](https://github.com/canonical/Ubuntu-fonts/assets/1124347/a4abf4a3-39df-4db5-947e-5efe158ad3a3)

**Comment by glenda-tn** [comment]
@djrrb if that can be done (removing anchors in the build process) then yes, please do it as this has regressed a couple times now. Those marks should be spacing.

**Comment by djrrb** [comment]
Looks like there is a recent discussion about this that might spark some changes to Glyphsapp:

https://forum.glyphsapp.com/t/fontbakery-warn-check-glyphs-in-mark-glyph-class-are-non-spacing/26414/13

There is a temporary measure that fixes the GDEF class with fontTools, that we could try to adapt:

https://github.com/mekkablue/Glyphs-Scripts/blob/66337f87944c73367b3bcaf10584a2f934756f96/Post%20Production/Fix%20GDEF%20class%20definition%20of%20Legacy%20Marks.py

**Comment by guidoferreyra** [comment]
I will see to implement this on the building script ASAP.
