### ISSUE TITLE
Marks are not placed correctly on `f_i`

### ISSUE THREAD

**Issue by dscorbett** [canonical/Ubuntu-fonts#108]
Marks are not placed correctly on `f_i`. For example, here is <U+0066, U+0311, U+0069, U+0329>:
![f̑i̩](https://github.com/canonical/Ubuntu-fonts/assets/1124347/5bf8e83c-be3c-4f06-89d5-b9c450949d22)

Compare `f_f_i`, on which marks are placed correctly, as in <U+0066, U+0311, U+0066, U+0311, U+0069, U+0329>:
![f̑f̑i̩](https://github.com/canonical/Ubuntu-fonts/assets/1124347/fa14e2ba-6955-4ca4-8e28-d18e4792f0f1)

**Comment by djrrb** [comment]
Ok I think this is looking better:

<img width="1917" alt="Screenshot 2023-08-17 at 5 28 31 PM" src="https://github.com/canonical/Ubuntu-fonts/assets/6578861/6eb7bef5-c06e-4b5e-a6f7-1ba2ffb32639">

**Comment by dscorbett** [comment]
The mark above the ⟨f⟩ in the ⟨fi⟩ ligature in that image looks a bit too far to the left.

**Comment by djrrb** [comment]
Haha I noticed that too right after I posted, thanks!

**Comment by djrrb** [comment]
```f̑i̩ f̑f̑i̩```

<img width="1191" alt="Screenshot 2023-08-18 at 3 40 33 PM" src="https://github.com/canonical/Ubuntu-fonts/assets/6578861/e512d5e0-9373-47a4-9526-395dd5e1a80b">

😌
