### ISSUE TITLE
Incorrect small capital forms

### ISSUE THREAD

**Issue by dscorbett** [canonical/Ubuntu-fonts#109]
Some characters have incorrect small capital forms:

* U+01BA LATIN SMALL LETTER EZH WITH TAIL
* U+019B LATIN SMALL LETTER LAMBDA WITH STROKE
* U+1FB6 GREEK SMALL LETTER ALPHA WITH PERISPOMENI
* U+1FC6 GREEK SMALL LETTER ETA WITH PERISPOMENI
* U+0069 LATIN SMALL LETTER I (when the language system is Turkish)

![ƺƛᾶῆi](https://github.com/canonical/Ubuntu-fonts/assets/1124347/cce268f9-54b0-4d44-8b23-80fab1d65cac)

Compare the lowercase forms:
![ƺƛᾶῆi](https://github.com/canonical/Ubuntu-fonts/assets/1124347/5d5486f3-6edc-4b3b-aab7-d1656566db82)

**Comment by djrrb** [comment]
Thanks! Note to self, what the lambda should apparently look like: 

https://en.wikipedia.org/wiki/Barred_lambda

**Comment by djrrb** [comment]
* **ƺ** and **ƛ** do not have uppercase forms, so I have removed their small cap variants. I see in the wikipedia article above that a cap form for the barred lambda does exist, but is not supported in Unicode.

* **ᾶ** and **ῆ** now use the perispomeni diacritic

* I believe the dotted and dotless I are 

Using the test string ```ƺ ƛ ᾶ ῆ iı İI ```

Default arrangement:

<img width="2114" alt="Screenshot 2023-08-17 at 5 31 14 PM" src="https://github.com/canonical/Ubuntu-fonts/assets/6578861/665d1300-ec32-4b49-a651-c28e3962d634">

Lowercase to small caps applied:

<img width="2114" alt="Screenshot 2023-08-17 at 5 31 24 PM" src="https://github.com/canonical/Ubuntu-fonts/assets/6578861/01ef9e7f-7dd8-4189-a7b2-e8eddd51c003">

Lowercase to small caps applied, Turkish language:

<img width="2114" alt="Screenshot 2023-08-17 at 5 31 31 PM" src="https://github.com/canonical/Ubuntu-fonts/assets/6578861/f4ae6a7f-cd64-4dbd-93bc-3531123b9343">

Caps to small caps applied, Turkish language:

<img width="2114" alt="Screenshot 2023-08-17 at 5 31 31 PM" src="https://github.com/canonical/Ubuntu-fonts/assets/6578861/f4ae6a7f-cd64-4dbd-93bc-3531123b9343">

**Comment by djrrb** [comment]
@dscorbett I’m going to close this but feel free to reopen if you have further concerns about any of the above small cap glyphs.

**Comment by dscorbett** [comment]
Those images look good, except that the last one is captioned “Caps to small caps applied, Turkish language” but it is the same as the previous image, so I don’t know if Turkish 'c2sc' is correct.

**Comment by djrrb** [comment]
@dscorbett oops sorry about that, I just edited my previous comment to include the correct image.
