### ISSUE TITLE
Extracting discrete font from variable font

### ISSUE THREAD

**Issue by nteodosio** [canonical/Ubuntu-fonts#111]
I want to extract discrete fonts from this new Ubuntu font to test for [LP:2019045](launchpad.net/bugs/2019045). The command

    fonttools varLib.instancer -o /tmp/qUbuntu-B.ttf ./Ubuntu\[wdth\,wght\].ttf wdth=drop wght=700

does get one there, but the name of the font is still Ubuntu and the style is regular as far as fc-list and the consuming programs are concerned.

How can I extract the font to an arbitrary name and style?

**Comment by nteodosio** [comment]
Managed to do that with Fontforge: Element > Font Information.

**Comment by djrrb** [comment]
Glad you found a solution, @nteodosio !

If you prefer a command-line approach, you can also check out [OT Feature Freezer](https://github.com/twardoch/fonttools-opentype-feature-freezer) which has a somewhat-straightforward `--replacenames` argument. This is built on [FontTools](https://fonttools.readthedocs.io/en/latest/), which can also be used to modify the font’s `name` table directly (this can be a bit complicated as it might involve modifying multiple name records).

And just in case you didn’t see, premade static fonts for the named instances (including Bold) are also available here: https://github.com/canonical/Ubuntu-fonts/tree/main/fonts/ttf
