### ISSUE TITLE
Anchors

### ISSUE THREAD

**Issue by djrrb** [canonical/Ubuntu-fonts#3]
Original fonts had no anchors. 

I’m adding preliminary anchor support for better GPOS mark positioning when generated with fontmake, but making a note that more could be done to fine-tune positioning if GPOS is a priority.

**Comment by djrrb** [comment]
Gen and Zrinka repositioned all accents and anchors, which will hopefully help with consistency of accent positioning across the family and hopefully make future edits much easier.

**Comment by guidoferreyra** [comment]
This is major improvement 🎉

**Comment by guidoferreyra** [comment]
Anchors are present on the sources.
