### ISSUE TITLE
Add additional symbols

### ISSUE THREAD

**Issue by djrrb** [canonical/Ubuntu-fonts#34]
- [x] checkbox ✓ 
- [x] x mark ✗

**Comment by glenda-tn** [comment]
See #3. I also recommend that macronbelow.comb (u0320) and maybe the verticallinebelow.comb (u0329) also be added if possible.

**Comment by djrrb** [comment]
These have been added before e16eed91024b8f645f306c2ac6e17ee5307ea784 to the upright fonts, but the Italic and Mono versions are still in progress...sorry about that.

**Comment by guidoferreyra** [comment]
This is already completed
