### ISSUE TITLE
Version should be 1.000

### ISSUE THREAD

**Issue by guidoferreyra** [canonical/Ubuntu-fonts#54]
> 🔥 FAIL The NameID.VERSION_STRING (nameID=5) value must follow the pattern "Version X.Y" with X.Y greater than or equal to 1.000. Current version string is: "Version 0.863; ttfautohint (v1.8.4.7-5d5b)" [code: bad-version-strings]

Should we jump to v1.000?

**Comment by djrrb** [comment]
This seems necessary to pass Google Fonts QA, so I am going to bump the version number, but let’s make sure this is ok with all stakeholders before proceeding.

**Comment by djrrb** [comment]
Bumped in e16eed91024b8f645f306c2ac6e17ee5307ea784
