### ISSUE TITLE
Remove PUA codepoints from glyphs.

### ISSUE THREAD

**Issue by guidoferreyra** [canonical/Ubuntu-fonts#65]
Many glyphs are using PUA codepoints, we should remove it and double check are accesible through features.

**Comment by djrrb** [comment]
I agree we should put them in features and make sure the correct codepoints are used when possible, but I do hesitate to break backwards compatibility unless you think it’s required. @guidoferreyra can you confirm?

To have a record of the glyphs currently using PUA:

## Fractions

Only two of these have proper encodings. The `frac` feature handles other arbitrary fractions. Should we leave these using PUA?

- F506 oneseventh: also encode as `u+2150` ⅐
- F507 twosevenths
- F508 three sevenths
- F509 foursevenths
- F50A fivesevenths
- F50B sixsevenths
- F50C oneninth: also encode as `u+2151`  ⅑
- F50D twoninths
- F50E fourninths
- F50F fiveninths
- F510 sevenninths
- F511 eightninths

## Ligatures

- F001 fi: move to `U+FB01` ﬁ
- F002 fl: move to `U+FB02` ﬂ

## Proportional figures

Implemented via OpenType feature `pnum`, no encoding necessary. (Will also rename glyph name suffix to '.lf' for clarity.)

- F800 zero.alt
- F801 one.alt
- F802 two.alt
- F803 three.alt
- F804 four.alt
- F805 five.alt
- F806 six.alt
- F807 seven.alt
- F808 eight.alt
- F809 nine.alt

## Superiors and Inferiors

Use unicode [subscripts and superscripts](https://en.wikipedia.org/wiki/Superscripts_and_Subscripts_(Unicode_block)) instead or in addition.

- F80A zero.sups
- F80B one.sups 
- F80C two.sups
- F80D three.sups
- F80E four.sups
- F80F five.sups
- F810 six.sups
- F811 seven.sups
- F812 eight.sups
- F813 nine.sups
- F814 zero.sinf
- F815 one.sinf
- F816 two.sinf
- F817 three.sinf
- F818 four.sinf
- F819 five.sinf
- F81A six.sinf
- F81B seven.sinf
- F81C eight.sinf
- F81D nine.sinf

# Logos

Omitting from font.

- F200 ubuntu (wordmark)
- E0FF uniE0FF (logo)
- F0FF uniF0FF (superscript logo)
- F000 uniF000 (hinting glyph)

**Comment by guidoferreyra** [comment]
The font has other "breaking" changes to already consider it as new major release, so my opinion is the following:

Fractions: I don’t see what is the point of having those precomposed glyphs for very rare fractions. But if we need to keep them I think it’s better to remove the PUA to not alter user’s character string when activating the feature.

Ligatures: I agree

Proportional figures: I agree. +1 for the renaming too 

Superiors and Inferiors. To me just using the superior and inferior unicode values will be enough, no need to add PUA

**Comment by djrrb** [comment]
Ok sounds like a good plan, I will implement this shortly.

**Comment by djrrb** [comment]
Changed in e16eed91024b8f645f306c2ac6e17ee5307ea784

It’s a bit unusual because the encoded `zerosuperior` was set to the `numr` feature and the unencoded `zero.sups` is set to the `sups` feature. But I don‘t see a problem with that.
