### ISSUE TITLE
Ensure soft_dotted characters lose their dot when combined with marks that replace the dot.

### ISSUE THREAD

**Issue by glenda-tn** [canonical/Ubuntu-fonts#68]
This is a new Google FB check.

🔥 FAIL
The dot of soft dotted characters used in orthographies must disappear in the following strings: i̊ i̋ j̀ j́ j̃ j̄ j̈ j̑ į̀ į́ į̂ į̃ į̄ į̌ і́
The dot of soft dotted characters should disappear in other cases, for example: i̇ i̒ ị̇ ị̊ ị̋ ị̒ i̦̇ i̦̊ i̦̋ i̦̒ i̧̇ i̧̊ i̧̋ i̧̒ i̩̇ i̩̊ i̩̋ i̩̒ i̱̇ i̱̊ [code: soft-dotted]

<img width="799" alt="Screen Shot 2023-03-14 at 5 05 26 PM" src="https://user-images.githubusercontent.com/93950887/225169175-138f3e11-a154-44ec-ab23-0e1bb3f4afe2.png">

**Comment by glenda-tn** [comment]
@djrrb  `[here](https://github.com/googlefonts/fontbakery/issues/4059)` is the recent FB issue and the `ccmp` fix.

**Comment by djrrb** [comment]
So this link says that the `ccmp` code is optional, nor is it a complete and functioning example (there’s just an `#etc.` comment).

I’m hesitant to try to quickly hack together a `ccmp` that I don’t fully understand. @guidoferreyra is this something you think you could take a stab at, or since it says the code is optional do you think it makes sense to omit for now?

**Comment by guidoferreyra** [comment]
I’ve never used that specific solution since it’s quite new. But I’ve been using a similar, but not that much comprehensive, suggested by Glyphs App. 

```
lookup ccmp_Other_1 {
	@CombiningTopAccents = [acutecomb brevecomb breveinvertedcomb caroncomb circumflexcomb commaturnedabovecomb dblgravecomb dieresiscomb dotaccentcomb gravecomb hungarumlautcomb macroncomb ringcomb tildecomb];
	@CombiningNonTopAccents = [cedillacomb dotbelowcomb macronbelowcomb ogonekcomb verticallinebelowcomb];
	sub [i j]' @CombiningTopAccents by [idotless jdotless];
	sub [i j]' @CombiningNonTopAccents @CombiningTopAccents by [idotless jdotless];
} ccmp_Other_1;

```
