### ISSUE TITLE
jaggy segments

### ISSUE THREAD

**Issue by glenda-tn** [canonical/Ubuntu-fonts#70]
> This check heuristically detects outline segments which form a particularly small angle, indicative of an outline error. This may cause false positives in cases such as extreme ink traps, so should be regarded as advisory and backed up by manual inspection.

⚠️ UbuntuCondensed-Bold.ttf
⚠️ UbuntuCondensed-ExtraBold.ttf
⚠️ UbuntuCondensed-BoldItalic.ttf
⚠️ UbuntuCondensed-ExtraBoldItalic.ttf

The following glyphs have jaggy segments:
* trademark (U+2122)

I checked other reported glyphs but the look fine. These `™` look suspicious though. Please double check the outlines.
<img width="512" alt="Screen Shot 2023-03-14 at 5 48 54 PM" src="https://user-images.
<img width="512" alt="Screen Shot 2023-03-14 at 5 48 54 PM" src="https://user-images.githubusercontent.com/93950887/225175251-da4bccac-2820-4c68-ada0-ec218a22315b.png">
githubusercontent.com/93950887/225175231-b3710064-70ce-48ae-9210-abc808f5cec7.png">

**Comment by djrrb** [comment]
Oooh good catch!
