### ISSUE TITLE
frac feature

### ISSUE THREAD

**Issue by glenda-tn** [canonical/Ubuntu-fonts#73]
Whole numbers should **not** convert to `numr` when `frac` feature is implemented.
`1½ 1¼ 1¾ 6 3/4 1 1/2 3 2/3  1½ 1¼ 1¾ 6 3/4 1 1/2 3 2/3`

![Screen Shot 2023-03-15 at 12 58 30 AM](https://user-images.githubusercontent.com/93950887/225244356-a3d32d62-ff35-45f8-8d80-3aec73170af0.png)

**Comment by djrrb** [comment]
<img width="1829" alt="Screenshot 2023-03-16 at 9 49 22 AM" src="https://user-images.githubusercontent.com/6578861/225637689-27168468-654b-4e0a-85ac-a748a15848d6.png">
