### ISSUE TITLE
uni040E missing diacritic

### ISSUE THREAD

**Issue by glenda-tn** [canonical/Ubuntu-fonts#75]
[Ў U+040E CYRILLIC CAPITAL LETTER SHORT U](https://unicode-explorer.com/c/040E)

![Screen Shot 2023-03-15 at 1 30 19 PM](https://user-images.githubusercontent.com/93950887/225435015-1f0bf3d4-9853-4bc7-adfd-875d9590bb09.png)

**Comment by djrrb** [comment]
fixed!
