### ISSUE TITLE
c2sc, smcp, and case lkps

### ISSUE THREAD

**Issue by glenda-tn** [canonical/Ubuntu-fonts#76]
- [x] check guillumet alignment

![Screen Shot 2023-03-15 at 1 58 59 PM](https://user-images.githubusercontent.com/93950887/225441427-1474905b-7514-44d4-9372-bd137acf9287.png)

- [x] check synchronicity of space and alignments. This is happening in the Condensed styles.

![Screen Shot 2023-03-15 at 2 00 09 PM](https://user-images.githubusercontent.com/93950887/225444703-6a677ab9-3270-417a-85c3-2c09c3e3a17a.png)

Edited to remove previous comment. Noted: Ubuntu Italics and Condensed do not have small cap forms.

**Comment by glenda-tn** [comment]
- [ ] review hyphen/dash alignment in `case`
![Screen Shot 2023-03-15 at 2 45 13 PM](https://user-images.githubusercontent.com/93950887/225451415-8e6c0300-6a55-4d81-9aa7-1b46e8a651c2.png)

**Comment by djrrb** [comment]
Guillemets fixed. I’m inclined to let the dash alignments stand, since these variations seem more intentional.
