### ISSUE TITLE
Kra (uni0138) apostrophe 

### ISSUE THREAD

**Issue by glenda-tn** [canonical/Ubuntu-fonts#77]
Is apostrophe shape as intended?
![Screen Shot 2023-03-15 at 3 03 21 PM](https://user-images.githubusercontent.com/93950887/225454274-0773ec44-238f-48be-8a29-bc7380e35407.png)

**Comment by djrrb** [comment]
I believe so: https://en.wikipedia.org/wiki/Kra_(letter)

**Comment by glenda-tn** [comment]
Sorry, I should have been more specific. I'm meant the apostrophe used seems to be a _left_ apostrophe/quote while I think it should be the _right_.
