### ISSUE TITLE
rename uni03BC.1 as mu?

### ISSUE THREAD

**Issue by glenda-tn** [canonical/Ubuntu-fonts#78]
Should 00B5 be named `mu` or `uni00B5`? In the original version it was named `mu`.

![Screen Shot 2023-03-15 at 4 25 55 PM](https://user-images.githubusercontent.com/93950887/225466035-d1677513-4824-4983-8752-20e5b0d2d4d9.png)

**Comment by djrrb** [comment]
thanks, done!
