### ISSUE TITLE
Non-exporting glyphs are making it into the build

### ISSUE THREAD

**Issue by djrrb** [canonical/Ubuntu-fonts#80]
I have `--write-public-skip-export-glyphs` active for the `glyphs2ufo` command, but the non-exporting fonts are still making it into the OTF and TTF files. Can you disable this?

**Comment by guidoferreyra** [comment]
--write-public-skip-export-glyphs writes the list of glyphs to not export on the .designspace. I just updated [e6f8a4d](https://github.com/canonical/Ubuntu-fonts/commit/e6f8a4d5d8962bfc19ee4e3c1f0662579935167f) the dspace with the non exportable glyphs.
