### ISSUE TITLE
For support of Mizo language please add Ṭ and ṭ

### ISSUE THREAD

**Issue by KristijanZic** [canonical/Ubuntu-fonts#86]
There are two letters form the Mizo alphabet missing that's unicode `U+1E6C` and unicode `U+1E6D`.
More information on the letter can be found here: [https://en.wikipedia.org/wiki/%E1%B9%AC?useskin=vector](https://en.wikipedia.org/wiki/%E1%B9%AC?useskin=vector)

Could you please implement it properly into Ubuntu font family?

**Comment by KristijanZic** [comment]
@guidoferreyra I've tried to do it myself and managed to do it for Ubuntu-Regular with font forge but it took hours to do it with Font Forge crashing all the time. Unfortunately I don't have the licenses nor do I know how to use the software which you use to make Ubuntu font family.

Not to put any pressure but is there an ETA when this enhancement might land here and possibly in Google Fonts too?

**Comment by djrrb** [comment]
Hi there! I’ll be happy to add these glyphs to the next version of the font, which should be committed before the end of the month. I can’t give you a date on when this version will land on Google Fonts.

**Comment by KristijanZic** [comment]
> Hi there! I’ll be happy to add these glyphs to the next version of the font, which should be committed before the end of the month. I can’t give you a date on when this version will land on Google Fonts.

Any news?

**Comment by djrrb** [comment]
Apologies for the delay on this; these glyphs are now available in the fonts in the 0.869 branch:

https://github.com/canonical/Ubuntu-fonts/tree/0.869
https://github.com/canonical/UbuntuMono-fonts/tree/0.869

<img width="1199" alt="Screenshot 2023-05-30 at 3 24 27 PM" src="https://github.com/canonical/Ubuntu-fonts/assets/6578861/0327d57d-c2fd-424e-a85a-23eeac9c0c81">

**Comment by djrrb** [comment]
<img width="999" alt="Screenshot 2023-05-30 at 6 01 57 PM" src="https://github.com/canonical/Ubuntu-fonts/assets/6578861/a10714a9-5791-4370-9b9c-127d67a6f6b8">

**Comment by KristijanZic** [comment]
That's okay, I'm using Roboto but will hopefully move back to Ubuntu in an update now that it supports Mizo alphabet. Thank you very much, this will be greatly useful to over a million people!
