### ISSUE TITLE
[Registered] (and possibly other characters) rendered as a regular character rather than a superscript

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/Ubuntu-fonts#87]
In Ubuntu:
![image](https://user-images.githubusercontent.com/2741678/231804947-59c89f8b-2a88-4ec4-969d-25619ce11c9f.png)

In other typefaces, e.g. Calibri:
![image](https://user-images.githubusercontent.com/2741678/231804811-67bef728-403f-445a-a514-6ba13bccf3d2.png)

**Comment by lyubomir-popov** [comment]
hi @djrrb, I know this is outside the scope of the current work, but what is your opinion on this? Is this a bug in the original fonts that we've never noticed?

**Comment by xxdgwxx** [comment]
Hi @lyubomir-popov, I hope you don't mind me answering for @djrrb while he is out of the office. This is a feature, not a bug. Many fonts use a full-size registered symbol, which is more legible at text sizes. See [Microsoft Typography](https://learn.microsoft.com/en-us/typography/develop/character-design-standards/punctuation#:~:text=Copyright%20and%20registered%20trademark%20symbol%20%2D%20full%20size) for reference. A smaller, superscript ® is offered in some fonts for display sizes.

**Comment by lyubomir-popov** [comment]
I think a display version is a valid case for us - so will keep this open if you don't mind @xxdgwxx 
Here's an example of where we are currently using it, and it looks odd to me:

![image](https://user-images.githubusercontent.com/2741678/231993434-5e18717a-8a8c-4b7d-aab3-45d5d103e7bc.png)

**Comment by xxdgwxx** [comment]
Sure, we can keep it open, and add it to our discussion.

**Comment by djrrb** [comment]
I went ahead and made the superscript the default in v1.000.
