### ISSUE TITLE
Issues from testing in Ubuntu OS at default font-size (11px)

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/Ubuntu-fonts#89]
Hi @djrrb, we have received a list of screenshots showing the typeface in various screens on the latest Ubuntu OS, which is using the variable fonts. Is there anything we can do to improve on those?: 

- letter i (and probably also j): Stem and dot merging (highlighted in red circles):
![image](https://user-images.githubusercontent.com/2741678/232763428-d3be146a-aba1-4d3c-820d-b7b9fae23bdc.png)

- kerning issues (not sure if this can be improved without hinting):
![image](https://user-images.githubusercontent.com/2741678/232764287-9a39c1ea-e2da-4b90-98f6-04f6c2a24658.png)

Here's the folder, I'll ask for access so you can have a look too.

**Comment by djrrb** [comment]
Yeah I agree this is a big problem. There are some autohinting settings that we can futz with, but honestly I think the most robust solution might be to just raise the dot slightly.

**Comment by djrrb** [comment]
The i/j dots are now components and slightly further from the base glyph, and should perform better even when autohinted or unhinted. I’ll close this but feel free to reopen if the issue persists on your end.

**Comment by fitojb** [comment]
The new tittle position works great! Thanks @djrrb!

Before:
![Captura desde 2023-07-08 14-57-23](https://github.com/canonical/Ubuntu-fonts/assets/554953/28dd37bb-c9b8-4fb5-86ce-d03bc65a770b)

After:
![Captura desde 2023-07-08 14-57-31](https://github.com/canonical/Ubuntu-fonts/assets/554953/df20792b-2ab8-4e64-9f4b-c62141f3c0ea)
