### ISSUE TITLE
Interpolation error in Ubuntu Mono Italic

### ISSUE THREAD

**Issue by glenda-tn** [canonical/Ubuntu-fonts#91]
⚠️ WARN
Interpolation issues were found in the font:

- Contour 1 start point differs in glyph 'hcircumflex'
- Contour 0 start point differs in glyph 'circumflex.asc'

https://github.com/canonical/Ubuntu-fonts/assets/93950887/7e611cc7-2212-4bb2-9957-f2c3918a2b22

**Comment by djrrb** [comment]
Thanks so much for catching that! I will fix shortly

**Comment by glenda-tn** [comment]
I was looking at the wrong version. sorry! It is fine.
