### ISSUE TITLE
Korean character set not responding to weights under 400

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/Ubuntu-fonts#92]
![image](https://github.com/canonical/Ubuntu-fonts/assets/2741678/d7876379-c7b8-41fc-87e6-d0ee146dcafc)

**Comment by djrrb** [comment]
Hey Lyubo,

Korean character support is not included in the Ubuntu fonts, so I believe we are seeing a fallback font here. If the fallback font has a weight range that goes down to 100, it should work as expected.

I think I found the article you are referencing here: https://canonical.com/blog/18-04-end-of-standard-support-kr

Currently the font stack is ```"Ubuntu variable", "Ubuntu", -apple-system, "Segoe UI", "Roboto", "Oxygen", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif```, so depending on where the page is loaded, a different fallback font might be used, and the available weight range might be different.

In Chrome 113 on Mac OS 13, I can see that Apple SD Gothic Neo is being used:

<img width="1059" alt="Screenshot 2023-06-25 at 5 01 08 PM" src="https://github.com/canonical/Ubuntu-fonts/assets/6578861/f6e02462-0ade-4278-a153-4f82b32a4deb">

I’m guessing that’s coming from `-apple-system` but weirdly it doesn’t go to font-weight 100 when I set that manually (I also enlarged it so it’s easier to see). 

<img width="1059" alt="Screenshot 2023-06-25 at 4 54 59 PM" src="https://github.com/canonical/Ubuntu-fonts/assets/6578861/03f9f358-8c0a-46d4-968f-db98377f8368">

Strangely this works fine for me on Safari 16.4 with the whole weight range:

https://github.com/canonical/Ubuntu-fonts/assets/6578861/2d903d17-3be6-44e1-8b84-4ea3b1819d02

In Chrome, if I specify the font explicitly, I see the 100 weight as expected:

<img width="1059" alt="Screenshot 2023-06-25 at 4 56 30 PM" src="https://github.com/canonical/Ubuntu-fonts/assets/6578861/701c74f1-53f2-4efd-ba93-16e37c5bbfc3">

I’m not sure why this didn’t work in Chrome with `-apple-system`, but I don’t believe it is related to the Ubuntu fonts, and I believe it can be remedied by amending the font stack. Let me know what you think!

**Comment by lyubomir-popov** [comment]
Thanks @djrrb, that makes sense, don't know why it didn't occur to me. I'm going to close the issue, and thanks for the suggestion of updating the font stack. We will look into it.

**Comment by xxdgwxx** [comment]
I know this is closed, but on the topic, if you're interested in expanding the character set to include Traditional Chinese, Simplified Chinese, Chinese regional variants, Korean, or Japanese (and many other writing systems for that matter), we're happy to connect you with our partners in Asia.
