### ISSUE TITLE
[Google Fonts specific] Check a font's STAT table contains compulsory Axis Values.

### ISSUE THREAD

**Issue by guidoferreyra** [canonical/Ubuntu-fonts#96]
Check ID: <FontBakeryCheck:com.google.fonts/check/STAT>
🔥 fonts/variable/Ubuntu-Italic[wdth,wght].ttf

    🔥 FAIL Compulsory STAT Axis Values are incorrect:

| Name | Axis | Current Value | Current Flags | Current LinkedValue | Expected Value | Expected Flags | Expected LinkedValue |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Normal | wdth | 100.0 | 2 | None | 100.0 | 2 | None |
| Condensed | wdth | 75.0 | 0 | None | 75.0 | 0 | None |
| SemiCondensed | wdth | N/A | N/A | N/A | 87.5 | 0 | None |
| Thin | wght | 100.0 | 0 | None | 100.0 | 0 | None |
| ExtraLight | wght | N/A | N/A | N/A | 200.0 | 0 | None |
| Light | wght | 300.0 | 0 | None | 300.0 | 0 | None |
| Regular | wght | 400.0 | 2 | 700.0 | 400.0 | 2 | 700.0 |
| Medium | wght | 500.0 | 0 | None | 500.0 | 0 | None |
| SemiBold | wght | N/A | N/A | N/A | 600.0 | 0 | None |
| Bold | wght | 700.0 | 0 | None | 700.0 | 0 | None |
| ExtraBold | wght | 800.0 | 0 | None | 800.0 | 0 | None |

**Comment by djrrb** [comment]
Related to #97...SemiCondensed, ExtraLight, and SemiBold were not in the original family and don’t seem strictly necessary now, but I’m not going to put up a fight if folks want them added.

**Comment by m4rc1e** [comment]
Perfect. Thank you very much!
